export const USERS_REPOSITORY = Symbol('USERS_REPOSITORY');
export const ROLES_REPOSITORY = Symbol('ROLES_REPOSITORY');
export const MODULES_REPOSITORY = Symbol('MODULES_REPOSITORY');
export const REFRESH_TOKENS_REPOSITORY = Symbol('REFRESH_TOKENS_REPOSITORY');
export const AUDIT_LOG_REPOSITORY = Symbol('AUDIT_LOG_REPOSITORY');
export const TOKEN_SERVICE = Symbol('TOKEN_SERVICE');
export const PERMISSIONS_SERVICE = Symbol('PERMISSIONS_SERVICE');
